### ISSUE TITLE
add -std=c++11 by default

### ISSUE THREAD

**Issue by jjdredd** [alisw/AliRoot#299]
By default after running cmake and trying to build the project, the build stops requiring c++11 support
from the compiler. Since it's required anyway, something like `-std=c++11` can be added to cmakelists
by default.

**Comment by pzhristov** [comment]
Hi @jjdredd, this is treated correctly by the build system. The default C++ flags can be seen here

https://github.com/alisw/alidist/blob/master/defaults-release.sh

The configuration of each package is available in the corresponding script:

https://github.com/alisw/alidist

I strongly advise the usage of the build system for the installation, see

https://dberzano.github.io/alice/install-aliroot/

**Comment by jjdredd** [comment]
The build system is cmake and make. They must be defined in cmake configuration files.
Not having to write another build system is the point of using cmake

**Comment by pzhristov** [comment]
We have more than one package to install and the consistent propagation of the compilation options is essential. If you do not want to use alibuild, you can specify the additional compilation options in the cmake configuration line manually. However, we do not plan to add -std=c++11 to the CMakeLists.txt.

**Comment by jjdredd** [comment]
What's the point of using cmake if you have another build system?

**Comment by pzhristov** [comment]
AliBuild is set of scripts that takes care of the consistent build between the different packages. It is not "another build system", the job is done by cmake. Your example is correct: instead of adding -std=c++11 to each individual package, it is in the defaults and the individual cmake calls are using it to configure. Now if we move to -std=c++14, we have to change only one place and not in several individual CMakeLists.txt. On the other hand, I admit if the compilation of a package is not possible without a flag, it has to be included in CMakeLists.txt.

**Comment by dberzano** [comment]
Hi @jjdredd, discussions concerning this repository are not carried on on GitHub issues. If you are a legitimate ALICE user then you have the credentials to open a new issue to our JIRA. That said, CMake and aliBuild are not quite the same category of software, unless on your computer you are used to run `cmake install emacs` to install your favorite editor.

**Comment by jjdredd** [comment]
Are you implying that you're alibuild is a package manager?
